---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: chef/centos-12.04
      customize:
        memory: 512
        cpuexecutioncap: 50

suites:
  - name: default
    run_list:
      - recipe[opencv::default]
    attributes: {}
